services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db
      - redis
  db:
    image: kiskolabs/postgres-fi:latest
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=changeme
      - LC_COLLATE=fi_FI.UTF-8
    volumes:
      - pg_data:/var/lib/postgresql/data
  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
  bundle: